---

- name: Set hostname
  shell: hostname icDB1

# I have to ignore errors - after creation, vagrant will complain on reloading as root is already set
- name: Update configuration
  action: template src=etc/mysql/my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600
  notify:
    - start mysql

- name: Update mysql root password for all root accounts
  action: mysql_user name=root host={{ item }} password={{ database_root_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes
  notify:
    - restart mysql

- name: copy .my.cnf file with root password credentials
  template: src="home/my.cnf" dest="~/.my.cnf" owner=root mode=0600

- name: Create database for app
  mysql_db:
    name={{ database_name }} state=present
  ignore_errors: yes

- name: Update mysql user password for app
  mysql_user:
    name={{ database_user }}
    host={{ app_host }}
    password={{ database_password }}
    priv={{ database_name }}.*:ALL
  ignore_errors: yes

- name: Update mysql user password for app
  mysql_user:
    name={{ database_user }}
    host=localhost
    password={{ database_password }}
    priv={{ database_name }}.*:ALL
  ignore_errors: yes
