---

- name: Create project directories
  file: state=directory path={{ item.path }}
  with_items:
    - { path: "{{ www_latest_release_root_dir }}/{{ www_sf2_app_cache_dir }}" }
    - { path: "{{ www_latest_release_root_dir }}/{{ www_sf2_app_logs_dir }}" }

- name: Create project symlinks
  file: state=link src={{ item.path }} dest={{ item.dest }}
  with_items:
    - { path: "{{ www_libraries_root_dir }}/{{ www_vendors_dir }}", dest: "{{ www_latest_release_root_dir }}/{{ www_vendors_dir }}" }
    - { path: "{{ www_libraries_root_dir }}/{{ www_bower_dir }}", dest: "{{ www_latest_release_root_dir }}/{{ www_bower_dir }}" }
    - { path: "{{ www_libraries_root_dir }}/{{ www_node_dir }}", dest: "{{ www_latest_release_root_dir }}/{{ www_node_dir }}" }
    - { path: "{{ www_symfony2_root_dir }}/{{ www_sf2_app_sessions_dir }}", dest: "{{ www_latest_release_root_dir }}/{{ www_sf2_app_sessions_dir }}" }
    - { path: "{{ www_symfony2_root_dir }}/{{ www_sf2_web_uploads_dir }}", dest: "{{ www_latest_release_root_dir }}/{{ www_sf2_web_uploads_dir }}" }
  ignore_errors: yes

- name: Check if shared/app/config/parameters.yml exists
  stat: path={{ www_symfony2_root_dir }}/{{ www_sf2_app_parameters_path }}
  register: parameters_file_check
- name: Create symlink for app/config/parameters.yml from shared directory
  file: state=link src={{ www_symfony2_root_dir }}/{{ www_sf2_app_parameters_path }} dest={{ www_latest_release_root_dir }}/{{ www_sf2_app_parameters_path }}
  when: parameters_file_check.stat.exists
